chore: upgrade requests (#13020)
so that we upgrade urllib3 which sentry latest needs

Problem
running pip install -r ./requirements.txt worked fine

but running pip install -r ./requirements.txt && pip install -r ./requirements-dev.txt gave an error message

Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.13
    Uninstalling urllib3-1.26.13:
      Successfully uninstalled urllib3-1.26.13
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentry-sdk 1.11.1 requires urllib3>=1.26.11; python_version >= "3.6", but you have urllib3 1.26.5 which is incompatible.
Changes
Upgraded the requests library and regenerated the requirements files