Fix typeerror with path_actors query (#7464)
Fixes
> ee/clickhouse/queries/paths/paths_actors.py:30: error: Incompatible types in assignment (expression has type "PathFilter", base class "ActorBaseQuery" defined the type as "Filter")

Caused by parallel merges & weird typing-related issues.